name = "auto-elec-worker"
main = "src/index.js"
compatibility_date = "2026-03-01"

[triggers]
crons = ["0 4 * * *"]

[vars]
ELEC_API_URL = "http://wxykt.tiangong.edu.cn/charge/feeitem/getThirdData"
AUTHORIZATION = "Basic Y2hhcmdlOmNoYXJnZV9zZWNyZXQ="
USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.6668.101 Safari/537.36 Language/zh ColorScheme/Light wxwork/5.0.0 (MicroMessenger/6.2) WindowsWechat  MailPlugin_Electron WeMail embeddisk wwmver/3.26.500.638 noMediaCs/false"
ACCEPT_LANGUAGE = "zh-CN,zh;q=0.9"
ORIGIN = "http://wxykt.tiangong.edu.cn"
REFERER = "http://wxykt.tiangong.edu.cn/charge-app/"
FEEITEM_ID = "428"
FEE_TYPE = "IEC"
FEE_LEVEL = "4"
CAMPUS = "天津工业大学&天津工业大学"
BUILDING = "20161008184448464922&西苑7号楼"
FLOOR = "6&6层"
ROOM = "20161009111811624619&1栋609"
TARGETS_JSON = "[{\"id\":\"room609\",\"name\":\"宿舍609\",\"feeitemid\":\"428\",\"type\":\"IEC\",\"level\":\"4\",\"campus\":\"天津工业大学&天津工业大学\",\"building\":\"20161008184448464922&西苑7号楼\",\"floor\":\"6&6层\",\"room\":\"20161009111811624619&1栋609\"},{\"id\":\"room430\",\"name\":\"宿舍430\",\"feeitemid\":\"428\",\"type\":\"IEC\",\"level\":\"4\",\"campus\":\"天津工业大学&天津工业大学\",\"building\":\"20161008182912026394&西苑3号楼\",\"floor\":\"4&4层\",\"room\":\"20161008225841597249&1栋430\"}]"
TARGET_QUERY_INTERVAL_SECONDS = "80"
BALANCE_PATH = ""
NOTIFY_MODE = "always"
LOW_BALANCE_THRESHOLD = "30"
NAPCAT_API_URL = "http://api-napcat.yuum.me/"
NAPCAT_TARGET_TYPE = "group"
NAPCAT_GROUP_ID = "974786367"
NAPCAT_USER_ID = ""
STATE_KEY = "last_balance"

[observability]
enabled = true
